### ISSUE TITLE
Error when running in parallel

### ISSUE THREAD

**Issue by deivydasp** [cybersokari/allure-deployer-action#13]
Hi, we faced an issue when running multiple workflows at the same time and the same repository:

![Image](https://github.com/user-attachments/assets/86262eed-1486-4541-9362-f01d70314d44)

Do you have any suggestion how to avoid this issue?

**Comment by deivydasp** [comment]
@cybersokari any advise?

**Comment by cybersokari** [comment]
> [@cybersokari](https://github.com/cybersokari) any advise?

I did not cover this edge case and am now swamped with work.

I will advise you to run your workflows in parallel for now while I make time to attend to this.

**Comment by deivydasp** [comment]
I really like this plugin I hope you'll find time to fix this issue

**Comment by deivydasp** [comment]
@cybersokari  can you check pull request? https://github.com/cybersokari/allure-deployer-action/pull/14 
It is simple, just adding fetch before pushing to github pages.

**Comment by cybersokari** [comment]
@deivydasp Thanks for the PR and sorry for the delay.

I merged, made a few more changes, and released a new version, 1.9.7.

You can now use this action for multiple test reports in a single action run.

Example: https://github.com/cybersokari/allure-deployer-action/actions/runs/14432358370

**Comment by deivydasp** [comment]
Thanks @cybersokari I'll test it later

**Comment by deivydasp** [comment]
@cybersokari still getting error. Less often but still time to time appears. 

![Image](https://github.com/user-attachments/assets/f103a25d-69f2-4edd-98a8-6c15dbe34f62)

probably need retry mechanism or something smarter.

**Comment by cosmin-pcc** [comment]
Thank you for creating and sharing this action, it’s very much appreciated. I wanted to mention that I’m also encountering the 'branch is behind' error while using this action in parallel jobs. It would be fantastic if a fix for this could be considered. Thank you again for your efforts!
